version: '3.9'

services:
    djangoapp:
        container_name: apiservice_djangoapp
        build:
            context: .
        ports:
        - 127.0.0.1:8001:8000
        volumes:
        - ./djangoapp:/djangoapp
        - static_volume:/data/web/static/
        - media_volume:/data/web/media/
        env_file:
        - ./dotenv_files/.env
        depends_on:
        - psql
    psql:
        container_name: apiservice-psql
        image: postgres:17-alpine
        volumes:
        - ./data/postgres/data:/var/lib/postgresql/data/
        env_file:
        - ./dotenv_files/.env

volumes:
  static_volume:
  media_volume: